//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.832
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;



namespace CSIPPayCertify.EntityLayer
{
    
    
    /// <summary>
    /// System_log
    /// </summary>
    [Serializable()]
    [AttributeTable("System_log")]
    public class EntitySystem_log : Entity
    {
        
        private string _Log_date;
        
        /// <summary>
        /// Log_date
        /// </summary>
        public static string M_Log_date = "Log_date";
        
        private string _Log_Time;
        
        /// <summary>
        /// Log_Time
        /// </summary>
        public static string M_Log_Time = "Log_Time";
        
        private string _CustomerID;
        
        /// <summary>
        /// CustomerID
        /// </summary>
        public static string M_CustomerID = "CustomerID";
        
        private string _Log_Action;
        
        /// <summary>
        /// Log_Action
        /// </summary>
        public static string M_Log_Action = "Log_Action";
        
        private string _Serial_No;
        
        /// <summary>
        /// Serial_No
        /// </summary>
        public static string M_Serial_No = "Serial_No";
        
        private string _User_Name;
        
        /// <summary>
        /// User_Name
        /// </summary>
        public static string M_User_Name = "User_Name";
        
        private string _User_ID;
        
        /// <summary>
        /// User_ID
        /// </summary>
        public static string M_User_ID = "User_ID";

        private string _System_Type;

        /// <summary>
        /// System_Type
        /// </summary>
        public static string M_System_Type = "System_Type";
        
        /// <summary>
        /// Log_date
        /// </summary>
        [AttributeField("Log_date", "System.String", false, false, false, "String")]
        public string Log_date
        {
            get
            {
                return this._Log_date;
            }
            set
            {
                this._Log_date = value;
            }
        }
        
        /// <summary>
        /// Log_Time
        /// </summary>
        [AttributeField("Log_Time", "System.String", false, false, false, "String")]
        public string Log_Time
        {
            get
            {
                return this._Log_Time;
            }
            set
            {
                this._Log_Time = value;
            }
        }
        
        /// <summary>
        /// CustomerID
        /// </summary>
        [AttributeField("CustomerID", "System.String", false, false, false, "String")]
        public string CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this._CustomerID = value;
            }
        }
        
        /// <summary>
        /// Log_Action
        /// </summary>
        [AttributeField("Log_Action", "System.String", false, false, false, "String")]
        public string Log_Action
        {
            get
            {
                return this._Log_Action;
            }
            set
            {
                this._Log_Action = value;
            }
        }
        
        /// <summary>
        /// Serial_No
        /// </summary>
        [AttributeField("Serial_No", "System.String", false, false, false, "String")]
        public string Serial_No
        {
            get
            {
                return this._Serial_No;
            }
            set
            {
                this._Serial_No = value;
            }
        }
        
        /// <summary>
        /// User_Name
        /// </summary>
        [AttributeField("User_Name", "System.String", false, false, false, "String")]
        public string User_Name
        {
            get
            {
                return this._User_Name;
            }
            set
            {
                this._User_Name = value;
            }
        }
        
        /// <summary>
        /// User_ID
        /// </summary>
        [AttributeField("User_ID", "System.String", false, false, false, "String")]
        public string User_ID
        {
            get
            {
                return this._User_ID;
            }
            set
            {
                this._User_ID = value;
            }
        }
        /// <summary>
        /// System_Type
        /// </summary>
        [AttributeField("System_Type", "System.String", false, false, false, "String")]
        public string System_Type
        {
            get
            {
                return this._System_Type;
            }
            set
            {
                this._System_Type = value;
            }
        }
    }
    
    /// <summary>
    /// System_log
    /// </summary>
    [Serializable()]
    public class EntitySystem_logSet : EntitySet<EntitySystem_log>
    {
    }
}
