//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.832
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPPayCertify.EntityLayer
{
    
    
    /// <summary>
    /// EntityPay_SerialSV
    /// </summary>
    [Serializable()]
    [AttributeTable("Pay_SerialSV")]
    public class EntityPay_SerialSV : Entity
    {
        
        private string _SERIALNO;
        
        /// <summary>
        /// SERIALNO
        /// </summary>
        public static string M_SERIALNO = "SERIALNO";

        private string _DAY;
        
        /// <summary>
        /// DAY
        /// </summary>
        public static string M_DAY = "DAY";
        
        private decimal _CURRENTNO;
        
        /// <summary>
        /// CURRENTNO
        /// </summary>
        public static string M_CURRENTNO = "CURRENTNO";
        
        /// <summary>
        /// SERIALNO
        /// </summary>
        [AttributeField("SERIALNO", "System.String", false, false, false, "String")]
        public string SERIALNO
        {
            get
            {
                return this._SERIALNO;
            }
            set
            {
                this._SERIALNO = value;
            }
        }
        
        /// <summary>
        /// DAY
        /// </summary>
        [AttributeField("DAY", "System.String", false, false, false, "String")]
        public string DAY
        {
            get
            {
                return this._DAY;
            }
            set
            {
                this._DAY = value;
            }
        }
        
        /// <summary>
        /// CURRENTNO
        /// </summary>
        [AttributeField("CURRENTNO", "System.Decimal", false, false, false, "Decimal")]
        public decimal CURRENTNO
        {
            get
            {
                return this._CURRENTNO;
            }
            set
            {
                this._CURRENTNO = value;
            }
        }
    }
    
    /// <summary>
    /// EntityPay_SerialSV
    /// </summary>
    [Serializable()]
    public class EntityPay_SerialSVSet : EntitySet<EntityPay_SerialSV>
    {
    }
}
