//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3082
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPPayCertify.EntityLayer
{
    
    
    /// <summary>
    /// EntityPay_Certify
    /// </summary>
    [Serializable()]
    [AttributeTable("Pay_Certify")]
    public class EntityPay_Certify : Entity
    {
        
        private string _serialNo;
        
        /// <summary>
        /// serialNo
        /// </summary>
        public static string M_serialNo = "serialNo";
        
        private string _userID;
        
        /// <summary>
        /// userID
        /// </summary>
        public static string M_userID = "userID";
        
        private string _userName;
        
        /// <summary>
        /// userName
        /// </summary>
        public static string M_userName = "userName";
        
        private string _add1;
        
        /// <summary>
        /// add1
        /// </summary>
        public static string M_add1 = "add1";
        
        private string _zip;
        
        /// <summary>
        /// zip
        /// </summary>
        public static string M_zip = "zip";
        
        private string _add2;
        
        /// <summary>
        /// add2
        /// </summary>
        public static string M_add2 = "add2";
        
        private string _add3;
        
        /// <summary>
        /// add3
        /// </summary>
        public static string M_add3 = "add3";
        
        private string _mailDay;
        
        /// <summary>
        /// mailDay
        /// </summary>
        public static string M_mailDay = "mailDay";
        
        private string _mailNo;
        
        /// <summary>
        /// mailNo
        /// </summary>
        public static string M_mailNo = "mailNo";
        
        private string _note;
        
        /// <summary>
        /// note
        /// </summary>
        public static string M_note = "note";
        
        private string _payName;
        
        /// <summary>
        /// payName
        /// </summary>
        public static string M_payName = "payName";
        
        private System.Nullable<int> _owe;
        
        /// <summary>
        /// owe
        /// </summary>
        public static string M_owe = "owe";
        
        private System.Nullable<int> _pay;
        
        /// <summary>
        /// pay
        /// </summary>
        public static string M_pay = "pay";
        
        private string _payDay;
        
        /// <summary>
        /// payDay
        /// </summary>
        public static string M_payDay = "payDay";
        
        private string _getFee;
        
        /// <summary>
        /// getFee
        /// </summary>
        public static string M_getFee = "getFee";
        
        private string _isMail;
        
        /// <summary>
        /// isMail
        /// </summary>
        public static string M_isMail = "isMail";
        
        private string _type;
        
        /// <summary>
        /// type
        /// </summary>
        public static string M_type = "type";
        
        private string _cardType;
        
        /// <summary>
        /// cardType
        /// </summary>
        public static string M_cardType = "cardType";
        
        private string _void;
        
        /// <summary>
        /// void
        /// </summary>
        public static string M_void = "void";
        
        private string _keyinDay;
        
        /// <summary>
        /// keyinDay
        /// </summary>
        public static string M_keyinDay = "keyinDay";
        
        private string _showExtra;
        
        /// <summary>
        /// showExtra
        /// </summary>
        public static string M_showExtra = "showExtra";
        
        private string _openDay;
        
        /// <summary>
        /// openDay
        /// </summary>
        public static string M_openDay = "openDay";
        
        private string _closeDay;
        
        /// <summary>
        /// closeDay
        /// </summary>
        public static string M_closeDay = "closeDay";
        
        private string _consignee;
        
        /// <summary>
        /// consignee
        /// </summary>
        public static string M_consignee = "consignee";
        
        private string _enddate;
        
        /// <summary>
        /// enddate
        /// </summary>
        public static string M_enddate = "enddate";
        
        private string _makeUp;
        
        /// <summary>
        /// makeUp
        /// </summary>
        public static string M_makeUp = "makeUp";
        
        private string _makeUpDate;
        
        /// <summary>
        /// makeUpDate
        /// </summary>
        public static string M_makeUpDate = "makeUpDate";
        
        private string _mailMethod;
        
        /// <summary>
        /// mailMethod
        /// </summary>
        public static string M_mailMethod = "mailMethod";
        
        private string _mainCard4E;
        
        /// <summary>
        /// mainCard4E
        /// </summary>
        public static string M_mainCard4E = "mainCard4E";

        private string _MakeUpOther;

        /// <summary>
        /// MakeUpOther
        /// </summary>
        public static string M_MakeUpOther = "MakeUpOther";

        private string _IsFree;

        /// <summary>
        /// IsFree
        /// </summary>
        public static string M_IsFree = "IsFree";

        // 20220425 RQ-2022-003727-000_開立清償證明系統-長姓名專案 By Kelton
        private string _LONG_NAME;

        /// <summary>
        /// LONG_NAME
        /// </summary>
        public static string M_LONG_NAME = "LONG_NAME";

        private string _ROMA;

        /// <summary>
        /// ROMA
        /// </summary>
        public static string M_ROMA = "ROMA";

        private string _HTGMsg;

        /// <summary>
        /// HTGMsg
        /// </summary>
        public static string M_HTGMsg = "HTGMsg";

        /// <summary>
        /// serialNo
        /// </summary>
        [AttributeField("serialNo", "System.String", false, false, false, "String")]
        public string serialNo
        {
            get
            {
                return this._serialNo;
            }
            set
            {
                this._serialNo = value;
            }
        }
        
        /// <summary>
        /// userID
        /// </summary>
        [AttributeField("userID", "System.String", false, false, false, "String")]
        public string userID
        {
            get
            {
                return this._userID;
            }
            set
            {
                this._userID = value;
            }
        }
        
        /// <summary>
        /// userName
        /// </summary>
        [AttributeField("userName", "System.String", false, false, false, "String")]
        public string userName
        {
            get
            {
                return this._userName;
            }
            set
            {
                this._userName = value;
            }
        }
        
        /// <summary>
        /// add1
        /// </summary>
        [AttributeField("add1", "System.String", false, false, false, "String")]
        public string add1
        {
            get
            {
                return this._add1;
            }
            set
            {
                this._add1 = value;
            }
        }
        
        /// <summary>
        /// zip
        /// </summary>
        [AttributeField("zip", "System.String", false, false, false, "String")]
        public string zip
        {
            get
            {
                return this._zip;
            }
            set
            {
                this._zip = value;
            }
        }
        
        /// <summary>
        /// add2
        /// </summary>
        [AttributeField("add2", "System.String", false, false, false, "String")]
        public string add2
        {
            get
            {
                return this._add2;
            }
            set
            {
                this._add2 = value;
            }
        }
        
        /// <summary>
        /// add3
        /// </summary>
        [AttributeField("add3", "System.String", false, false, false, "String")]
        public string add3
        {
            get
            {
                return this._add3;
            }
            set
            {
                this._add3 = value;
            }
        }
        
        /// <summary>
        /// mailDay
        /// </summary>
        [AttributeField("mailDay", "System.String", false, false, false, "String")]
        public string mailDay
        {
            get
            {
                return this._mailDay;
            }
            set
            {
                this._mailDay = value;
            }
        }
        
        /// <summary>
        /// mailNo
        /// </summary>
        [AttributeField("mailNo", "System.String", false, false, false, "String")]
        public string mailNo
        {
            get
            {
                return this._mailNo;
            }
            set
            {
                this._mailNo = value;
            }
        }
        
        /// <summary>
        /// note
        /// </summary>
        [AttributeField("note", "System.String", false, false, false, "String")]
        public string note
        {
            get
            {
                return this._note;
            }
            set
            {
                this._note = value;
            }
        }
        
        /// <summary>
        /// payName
        /// </summary>
        [AttributeField("payName", "System.String", false, false, false, "String")]
        public string payName
        {
            get
            {
                return this._payName;
            }
            set
            {
                this._payName = value;
            }
        }
        
        /// <summary>
        /// owe
        /// </summary>
        [AttributeField("owe", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> owe
        {
            get
            {
                return this._owe;
            }
            set
            {
                this._owe = value;
            }
        }
        
        /// <summary>
        /// pay
        /// </summary>
        [AttributeField("pay", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> pay
        {
            get
            {
                return this._pay;
            }
            set
            {
                this._pay = value;
            }
        }
        
        /// <summary>
        /// payDay
        /// </summary>
        [AttributeField("payDay", "System.String", false, false, false, "String")]
        public string payDay
        {
            get
            {
                return this._payDay;
            }
            set
            {
                this._payDay = value;
            }
        }
        
        /// <summary>
        /// getFee
        /// </summary>
        [AttributeField("getFee", "System.String", false, false, false, "String")]
        public string getFee
        {
            get
            {
                return this._getFee;
            }
            set
            {
                this._getFee = value;
            }
        }
        
        /// <summary>
        /// isMail
        /// </summary>
        [AttributeField("isMail", "System.String", false, false, false, "String")]
        public string isMail
        {
            get
            {
                return this._isMail;
            }
            set
            {
                this._isMail = value;
            }
        }
        
        /// <summary>
        /// type
        /// </summary>
        [AttributeField("type", "System.String", false, false, false, "String")]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        /// <summary>
        /// cardType
        /// </summary>
        [AttributeField("cardType", "System.String", false, false, false, "String")]
        public string cardType
        {
            get
            {
                return this._cardType;
            }
            set
            {
                this._cardType = value;
            }
        }
        
        /// <summary>
        /// void
        /// </summary>
        [AttributeField("void", "System.String", false, false, false, "String")]
        public string @void
        {
            get
            {
                return this._void;
            }
            set
            {
                this._void = value;
            }
        }
        
        /// <summary>
        /// keyinDay
        /// </summary>
        [AttributeField("keyinDay", "System.String", false, false, false, "String")]
        public string keyinDay
        {
            get
            {
                return this._keyinDay;
            }
            set
            {
                this._keyinDay = value;
            }
        }
        
        /// <summary>
        /// showExtra
        /// </summary>
        [AttributeField("showExtra", "System.String", false, false, false, "String")]
        public string showExtra
        {
            get
            {
                return this._showExtra;
            }
            set
            {
                this._showExtra = value;
            }
        }
        
        /// <summary>
        /// openDay
        /// </summary>
        [AttributeField("openDay", "System.String", false, false, false, "String")]
        public string openDay
        {
            get
            {
                return this._openDay;
            }
            set
            {
                this._openDay = value;
            }
        }
        
        /// <summary>
        /// closeDay
        /// </summary>
        [AttributeField("closeDay", "System.String", false, false, false, "String")]
        public string closeDay
        {
            get
            {
                return this._closeDay;
            }
            set
            {
                this._closeDay = value;
            }
        }
        
        /// <summary>
        /// consignee
        /// </summary>
        [AttributeField("consignee", "System.String", false, false, false, "String")]
        public string consignee
        {
            get
            {
                return this._consignee;
            }
            set
            {
                this._consignee = value;
            }
        }
        
        /// <summary>
        /// enddate
        /// </summary>
        [AttributeField("enddate", "System.String", false, false, false, "String")]
        public string enddate
        {
            get
            {
                return this._enddate;
            }
            set
            {
                this._enddate = value;
            }
        }
        
        /// <summary>
        /// makeUp
        /// </summary>
        [AttributeField("makeUp", "System.String", false, false, false, "String")]
        public string makeUp
        {
            get
            {
                return this._makeUp;
            }
            set
            {
                this._makeUp = value;
            }
        }
        
        /// <summary>
        /// makeUpDate
        /// </summary>
        [AttributeField("makeUpDate", "System.String", false, false, false, "String")]
        public string makeUpDate
        {
            get
            {
                return this._makeUpDate;
            }
            set
            {
                this._makeUpDate = value;
            }
        }
        
        /// <summary>
        /// mailMethod
        /// </summary>
        [AttributeField("mailMethod", "System.String", false, false, false, "String")]
        public string mailMethod
        {
            get
            {
                return this._mailMethod;
            }
            set
            {
                this._mailMethod = value;
            }
        }
        
        /// <summary>
        /// mainCard4E
        /// </summary>
        [AttributeField("mainCard4E", "System.String", false, false, false, "String")]
        public string mainCard4E
        {
            get
            {
                return this._mainCard4E;
            }
            set
            {
                this._mainCard4E = value;
            }
        }

        /// <summary>
        /// MakeUpOther
        /// </summary>
        [AttributeField("MakeUpOther", "System.String", false, false, false, "String")]
        public string MakeUpOther
        {
            get
            {
                return this._MakeUpOther;
            }
            set
            {
                this._MakeUpOther = value;
            }
        }

        /// <summary>
        /// IsFree
        /// </summary>
        [AttributeField("IsFree", "System.String", false, false, false, "String")]
        public string IsFree
        {
            get
            {
                return this._IsFree;
            }
            set
            {
                this._IsFree = value;
            }
        }

        // 20220425 RQ-2022-003727-000_開立清償證明系統-長姓名專案 By Kelton
        /// <summary>
        /// LONG_NAME
        /// </summary>
        [AttributeField("LONG_NAME", "System.String", false, false, false, "String")]
        public string LONG_NAME
        {
            get
            {
                return this._LONG_NAME;
            }
            set
            {
                this._LONG_NAME = value;
            }
        }

        /// <summary>
        /// ROMA
        /// </summary>
        [AttributeField("ROMA", "System.String", false, false, false, "String")]
        public string ROMA
        {
            get
            {
                return this._ROMA;
            }
            set
            {
                this._ROMA = value;
            }
        }

        /// <summary>
        /// HTGMsg
        /// </summary>
        [AttributeField("HTGMsg", "System.String", false, false, false, "String")]
        public string HTGMsg
        {
            get
            {
                return this._HTGMsg;
            }
            set
            {
                this._HTGMsg = value;
            }
        }
    }
    
    /// <summary>
    /// EntityPay_Certify
    /// </summary>
    [Serializable()]
    public class EntityPay_CertifySet : EntitySet<EntityPay_Certify>
    {
    }
}
