//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.832
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPPayCertify.EntityLayer
{
    
    
    /// <summary>
    /// Set_Pay_Certify
    /// </summary>
    [Serializable()]
    [AttributeTable("Set_Pay_Certify")]
    public class EntitySet_Pay_Certify : Entity
    {
        
        private string _serialNo;
        
        /// <summary>
        /// serialNo
        /// </summary>
        public static string M_serialNo = "serialNo";
        
        private string _userID;
        
        /// <summary>
        /// userID
        /// </summary>
        public static string M_userID = "userID";
        
        private string _userName;
        
        /// <summary>
        /// userName
        /// </summary>
        public static string M_userName = "userName";
        
        private string _CardNo;
        
        /// <summary>
        /// CardNo
        /// </summary>
        public static string M_CardNo = "CardNo";
        
        private string _add1;
        
        /// <summary>
        /// add1
        /// </summary>
        public static string M_add1 = "add1";
        
        private string _zip;
        
        /// <summary>
        /// zip
        /// </summary>
        public static string M_zip = "zip";
        
        private string _add2;
        
        /// <summary>
        /// add2
        /// </summary>
        public static string M_add2 = "add2";
        
        private string _add3;
        
        /// <summary>
        /// add3
        /// </summary>
        public static string M_add3 = "add3";
        
        private string _note;
        
        /// <summary>
        /// note
        /// </summary>
        public static string M_note = "note";
        
        private string _payName;
        
        /// <summary>
        /// payName
        /// </summary>
        public static string M_payName = "payName";
        
        private System.Nullable<int> _owe;
        
        /// <summary>
        /// owe
        /// </summary>
        public static string M_owe = "owe";
        
        private System.Nullable<int> _pay;
        
        /// <summary>
        /// pay
        /// </summary>
        public static string M_pay = "pay";
        
        private string _payDay;
        
        /// <summary>
        /// payDay
        /// </summary>
        public static string M_payDay = "payDay";
        
        private string _isMail;
        
        /// <summary>
        /// isMail
        /// </summary>
        public static string M_isMail = "isMail";
        
        private string _MailType;
        
        /// <summary>
        /// MailType
        /// </summary>
        public static string M_MailType = "MailType";
        
        private string _mailDay;
        
        /// <summary>
        /// mailDay
        /// </summary>
        public static string M_mailDay = "mailDay";
        
        private string _mailNo;
        
        /// <summary>
        /// mailNo
        /// </summary>
        public static string M_mailNo = "mailNo";
        
        private string _type;
        
        /// <summary>
        /// type
        /// </summary>
        public static string M_type = "type";
        
        private string _keyinDay;
        
        /// <summary>
        /// keyinDay
        /// </summary>
        public static string M_keyinDay = "keyinDay";
        
        private string _keyinUser;
        
        /// <summary>
        /// keyinUser
        /// </summary>
        public static string M_keyinUser = "keyinUser";
        
        private string _void;
        
        /// <summary>
        /// void
        /// </summary>
        public static string M_void = "void";
        
        private string _voidDay;
        
        /// <summary>
        /// voidDay
        /// </summary>
        public static string M_voidDay = "voidDay";
        
        private string _RecvName;
        
        /// <summary>
        /// RecvName
        /// </summary>
        public static string M_RecvName = "RecvName";
        
        private string _LoanDate;
        
        /// <summary>
        /// LoanDate
        /// </summary>
        public static string M_LoanDate = "LoanDate";
        
        private string _PayOffDate;
        
        /// <summary>
        /// PayOffDate
        /// </summary>
        public static string M_PayOffDate = "PayOffDate";
        
        private System.Nullable<int> _PayOffAmt;
        
        /// <summary>
        /// PayOffAmt
        /// </summary>
        public static string M_PayOffAmt = "PayOffAmt";
        
        private string _BLK_Code;
        
        /// <summary>
        /// BLK_Code
        /// </summary>
        public static string M_BLK_Code = "BLK_Code";
        
        private string _Back_Date;
        
        /// <summary>
        /// Back_Date
        /// </summary>
        public static string M_Back_Date = "Back_Date";
        
        private string _BackNote;
        
        /// <summary>
        /// BackNote
        /// </summary>
        public static string M_BackNote = "BackNote";

        // 20220425 RQ-2022-003727-000_開立清償證明系統-長姓名專案 By Kelton
        private string _LONG_NAME;

        /// <summary>
        /// LONG_NAME
        /// </summary>
        public static string M_LONG_NAME = "LONG_NAME";

        private string _ROMA;

        /// <summary>
        /// ROMA
        /// </summary>
        public static string M_ROMA = "ROMA";

        private string _HTGMsg;

        /// <summary>
        /// HTGMsg
        /// </summary>
        public static string M_HTGMsg = "HTGMsg";

        /// <summary>
        /// serialNo
        /// </summary>
        [AttributeField("serialNo", "System.String", false, false, false, "String")]
        public string serialNo
        {
            get
            {
                return this._serialNo;
            }
            set
            {
                this._serialNo = value;
            }
        }
        
        /// <summary>
        /// userID
        /// </summary>
        [AttributeField("userID", "System.String", false, false, false, "String")]
        public string userID
        {
            get
            {
                return this._userID;
            }
            set
            {
                this._userID = value;
            }
        }
        
        /// <summary>
        /// userName
        /// </summary>
        [AttributeField("userName", "System.String", false, false, false, "String")]
        public string userName
        {
            get
            {
                return this._userName;
            }
            set
            {
                this._userName = value;
            }
        }
        
        /// <summary>
        /// CardNo
        /// </summary>
        [AttributeField("CardNo", "System.String", false, false, false, "String")]
        public string CardNo
        {
            get
            {
                return this._CardNo;
            }
            set
            {
                this._CardNo = value;
            }
        }
        
        /// <summary>
        /// add1
        /// </summary>
        [AttributeField("add1", "System.String", false, false, false, "String")]
        public string add1
        {
            get
            {
                return this._add1;
            }
            set
            {
                this._add1 = value;
            }
        }
        
        /// <summary>
        /// zip
        /// </summary>
        [AttributeField("zip", "System.String", false, false, false, "String")]
        public string zip
        {
            get
            {
                return this._zip;
            }
            set
            {
                this._zip = value;
            }
        }
        
        /// <summary>
        /// add2
        /// </summary>
        [AttributeField("add2", "System.String", false, false, false, "String")]
        public string add2
        {
            get
            {
                return this._add2;
            }
            set
            {
                this._add2 = value;
            }
        }
        
        /// <summary>
        /// add3
        /// </summary>
        [AttributeField("add3", "System.String", false, false, false, "String")]
        public string add3
        {
            get
            {
                return this._add3;
            }
            set
            {
                this._add3 = value;
            }
        }
        
        /// <summary>
        /// note
        /// </summary>
        [AttributeField("note", "System.String", false, false, false, "String")]
        public string note
        {
            get
            {
                return this._note;
            }
            set
            {
                this._note = value;
            }
        }
        
        /// <summary>
        /// payName
        /// </summary>
        [AttributeField("payName", "System.String", false, false, false, "String")]
        public string payName
        {
            get
            {
                return this._payName;
            }
            set
            {
                this._payName = value;
            }
        }
        
        /// <summary>
        /// owe
        /// </summary>
        [AttributeField("owe", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> owe
        {
            get
            {
                return this._owe;
            }
            set
            {
                this._owe = value;
            }
        }
        
        /// <summary>
        /// pay
        /// </summary>
        [AttributeField("pay", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> pay
        {
            get
            {
                return this._pay;
            }
            set
            {
                this._pay = value;
            }
        }
        
        /// <summary>
        /// payDay
        /// </summary>
        [AttributeField("payDay", "System.String", false, false, false, "String")]
        public string payDay
        {
            get
            {
                return this._payDay;
            }
            set
            {
                this._payDay = value;
            }
        }
        
        /// <summary>
        /// isMail
        /// </summary>
        [AttributeField("isMail", "System.String", false, false, false, "String")]
        public string isMail
        {
            get
            {
                return this._isMail;
            }
            set
            {
                this._isMail = value;
            }
        }
        
        /// <summary>
        /// MailType
        /// </summary>
        [AttributeField("MailType", "System.String", false, false, false, "String")]
        public string MailType
        {
            get
            {
                return this._MailType;
            }
            set
            {
                this._MailType = value;
            }
        }
        
        /// <summary>
        /// mailDay
        /// </summary>
        [AttributeField("mailDay", "System.String", false, false, false, "String")]
        public string mailDay
        {
            get
            {
                return this._mailDay;
            }
            set
            {
                this._mailDay = value;
            }
        }
        
        /// <summary>
        /// mailNo
        /// </summary>
        [AttributeField("mailNo", "System.String", false, false, false, "String")]
        public string mailNo
        {
            get
            {
                return this._mailNo;
            }
            set
            {
                this._mailNo = value;
            }
        }
        
        /// <summary>
        /// type
        /// </summary>
        [AttributeField("type", "System.String", false, false, false, "String")]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        /// <summary>
        /// keyinDay
        /// </summary>
        [AttributeField("keyinDay", "System.String", false, false, false, "String")]
        public string keyinDay
        {
            get
            {
                return this._keyinDay;
            }
            set
            {
                this._keyinDay = value;
            }
        }
        
        /// <summary>
        /// keyinUser
        /// </summary>
        [AttributeField("keyinUser", "System.String", false, false, false, "String")]
        public string keyinUser
        {
            get
            {
                return this._keyinUser;
            }
            set
            {
                this._keyinUser = value;
            }
        }
        
        /// <summary>
        /// void
        /// </summary>
        [AttributeField("void", "System.String", false, false, false, "String")]
        public string @void
        {
            get
            {
                return this._void;
            }
            set
            {
                this._void = value;
            }
        }
        
        /// <summary>
        /// voidDay
        /// </summary>
        [AttributeField("voidDay", "System.String", false, false, false, "String")]
        public string voidDay
        {
            get
            {
                return this._voidDay;
            }
            set
            {
                this._voidDay = value;
            }
        }
        
        /// <summary>
        /// RecvName
        /// </summary>
        [AttributeField("RecvName", "System.String", false, false, false, "String")]
        public string RecvName
        {
            get
            {
                return this._RecvName;
            }
            set
            {
                this._RecvName = value;
            }
        }
        
        /// <summary>
        /// LoanDate
        /// </summary>
        [AttributeField("LoanDate", "System.String", false, false, false, "String")]
        public string LoanDate
        {
            get
            {
                return this._LoanDate;
            }
            set
            {
                this._LoanDate = value;
            }
        }
        
        /// <summary>
        /// PayOffDate
        /// </summary>
        [AttributeField("PayOffDate", "System.String", false, false, false, "String")]
        public string PayOffDate
        {
            get
            {
                return this._PayOffDate;
            }
            set
            {
                this._PayOffDate = value;
            }
        }
        
        /// <summary>
        /// PayOffAmt
        /// </summary>
        [AttributeField("PayOffAmt", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> PayOffAmt
        {
            get
            {
                return this._PayOffAmt;
            }
            set
            {
                this._PayOffAmt = value;
            }
        }
        
        /// <summary>
        /// BLK_Code
        /// </summary>
        [AttributeField("BLK_Code", "System.String", false, false, false, "String")]
        public string BLK_Code
        {
            get
            {
                return this._BLK_Code;
            }
            set
            {
                this._BLK_Code = value;
            }
        }
        
        /// <summary>
        /// Back_Date
        /// </summary>
        [AttributeField("Back_Date", "System.String", false, false, false, "String")]
        public string Back_Date
        {
            get
            {
                return this._Back_Date;
            }
            set
            {
                this._Back_Date = value;
            }
        }
        
        /// <summary>
        /// BackNote
        /// </summary>
        [AttributeField("BackNote", "System.String", false, false, false, "String")]
        public string BackNote
        {
            get
            {
                return this._BackNote;
            }
            set
            {
                this._BackNote = value;
            }
        }

        // 20220425 RQ-2022-003727-000_開立清償證明系統-長姓名專案 By Kelton
        /// <summary>
        /// LONG_NAME
        /// </summary>
        [AttributeField("LONG_NAME", "System.String", false, false, false, "String")]
        public string LONG_NAME
        {
            get
            {
                return this._LONG_NAME;
            }
            set
            {
                this._LONG_NAME = value;
            }
        }

        /// <summary>
        /// ROMA
        /// </summary>
        [AttributeField("ROMA", "System.String", false, false, false, "String")]
        public string ROMA
        {
            get
            {
                return this._ROMA;
            }
            set
            {
                this._ROMA = value;
            }
        }

        /// <summary>
        /// HTGMsg
        /// </summary>
        [AttributeField("HTGMsg", "System.String", false, false, false, "String")]
        public string HTGMsg
        {
            get
            {
                return this._HTGMsg;
            }
            set
            {
                this._HTGMsg = value;
            }
        }
    }
    
    /// <summary>
    /// Set_Pay_Certify
    /// </summary>
    [Serializable()]
    public class EntitySet_Pay_CertifySet : EntitySet<EntitySet_Pay_Certify>
    {
    }
}
