//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.832
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPPayCertify.EntityLayer
{
    
    
    /// <summary>
    /// EntityPay_Card
    /// </summary>
    [Serializable()]
    [AttributeTable("Pay_Card")]
    public class EntityPay_Card : Entity
    {
        
        private string _SERIALNO;
        
        /// <summary>
        /// SERIALNO
        /// </summary>
        public static string M_SERIALNO = "SERIALNO";
        
        private decimal _NO;
        
        /// <summary>
        /// NO
        /// </summary>
        public static string M_NO = "NO";
        
        private string _CARDNO;
        
        /// <summary>
        /// CARDNO
        /// </summary>
        public static string M_CARDNO = "CARDNO";
        
        private string _CUSID;
        
        /// <summary>
        /// CUSID
        /// </summary>
        public static string M_CUSID = "CUSID";
        
        private string _CUSNAME;
        
        /// <summary>
        /// CUSNAME
        /// </summary>
        public static string M_CUSNAME = "CUSNAME";
        
        private string _OPENDAY;
        
        /// <summary>
        /// OPENDAY
        /// </summary>
        public static string M_OPENDAY = "OPENDAY";
        
        private string _CODE1;
        
        /// <summary>
        /// CODE1
        /// </summary>
        public static string M_CODE1 = "CODE1";
        
        private string _CLOSEDAY1;
        
        /// <summary>
        /// CLOSEDAY1
        /// </summary>
        public static string M_CLOSEDAY1 = "CLOSEDAY1";
        
        private string _CODE2;
        
        /// <summary>
        /// CODE2
        /// </summary>
        public static string M_CODE2 = "CODE2";
        
        private string _CLOSEDAY2;
        
        /// <summary>
        /// CLOSEDAY2
        /// </summary>
        public static string M_CLOSEDAY2 = "CLOSEDAY2";
        
        private string _TYPECARD;
        
        /// <summary>
        /// TYPECARD
        /// </summary>
        public static string M_TYPECARD = "TYPECARD";
        
        private string _CardTempId;
        
        /// <summary>
        /// CardTempId
        /// </summary>
        public static string M_CardTempId = "CardTempId";
        
        /// <summary>
        /// SERIALNO
        /// </summary>
        [AttributeField("SERIALNO", "System.String", false, true, false, "String")]
        public string SERIALNO
        {
            get
            {
                return this._SERIALNO;
            }
            set
            {
                this._SERIALNO = value;
            }
        }
        
        /// <summary>
        /// NO
        /// </summary>
        [AttributeField("NO", "System.Decimal", false, true, false, "Decimal")]
        public decimal NO
        {
            get
            {
                return this._NO;
            }
            set
            {
                this._NO = value;
            }
        }
        
        /// <summary>
        /// CARDNO
        /// </summary>
        [AttributeField("CARDNO", "System.String", false, false, false, "String")]
        public string CARDNO
        {
            get
            {
                return this._CARDNO;
            }
            set
            {
                this._CARDNO = value;
            }
        }
        
        /// <summary>
        /// CUSID
        /// </summary>
        [AttributeField("CUSID", "System.String", false, false, false, "String")]
        public string CUSID
        {
            get
            {
                return this._CUSID;
            }
            set
            {
                this._CUSID = value;
            }
        }
        
        /// <summary>
        /// CUSNAME
        /// </summary>
        [AttributeField("CUSNAME", "System.String", false, false, false, "String")]
        public string CUSNAME
        {
            get
            {
                return this._CUSNAME;
            }
            set
            {
                this._CUSNAME = value;
            }
        }
        
        /// <summary>
        /// OPENDAY
        /// </summary>
        [AttributeField("OPENDAY", "System.String", false, false, false, "String")]
        public string OPENDAY
        {
            get
            {
                return this._OPENDAY;
            }
            set
            {
                this._OPENDAY = value;
            }
        }
        
        /// <summary>
        /// CODE1
        /// </summary>
        [AttributeField("CODE1", "System.String", false, false, false, "String")]
        public string CODE1
        {
            get
            {
                return this._CODE1;
            }
            set
            {
                this._CODE1 = value;
            }
        }
        
        /// <summary>
        /// CLOSEDAY1
        /// </summary>
        [AttributeField("CLOSEDAY1", "System.String", false, false, false, "String")]
        public string CLOSEDAY1
        {
            get
            {
                return this._CLOSEDAY1;
            }
            set
            {
                this._CLOSEDAY1 = value;
            }
        }
        
        /// <summary>
        /// CODE2
        /// </summary>
        [AttributeField("CODE2", "System.String", false, false, false, "String")]
        public string CODE2
        {
            get
            {
                return this._CODE2;
            }
            set
            {
                this._CODE2 = value;
            }
        }
        
        /// <summary>
        /// CLOSEDAY2
        /// </summary>
        [AttributeField("CLOSEDAY2", "System.String", false, false, false, "String")]
        public string CLOSEDAY2
        {
            get
            {
                return this._CLOSEDAY2;
            }
            set
            {
                this._CLOSEDAY2 = value;
            }
        }
        
        /// <summary>
        /// TYPECARD
        /// </summary>
        [AttributeField("TYPECARD", "System.String", false, false, false, "String")]
        public string TYPECARD
        {
            get
            {
                return this._TYPECARD;
            }
            set
            {
                this._TYPECARD = value;
            }
        }
        
        /// <summary>
        /// CardTempId
        /// </summary>
        [AttributeField("CardTempId", "System.String", false, false, false, "String")]
        public string CardTempId
        {
            get
            {
                return this._CardTempId;
            }
            set
            {
                this._CardTempId = value;
            }
        }
    }
    
    /// <summary>
    /// EntityPay_Card
    /// </summary>
    [Serializable()]
    public class EntityPay_CardSet : EntitySet<EntityPay_Card>
    {
    }
}
