//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3082
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPPayCertify.EntityLayer
{
    
    
    /// <summary>
    /// EntityPay_Macro
    /// </summary>
    [Serializable()]
    [AttributeTable("Pay_Macro")]
    public class EntityPay_Macro : Entity
    {
        
        private string _M_CUST_ID;
        
        /// <summary>
        /// M_CUST_ID
        /// </summary>
        public static string M_M_CUST_ID = "M_CUST_ID";
        
        private string _M_CUST_NAME;
        
        /// <summary>
        /// M_CUST_NAME
        /// </summary>
        public static string M_M_CUST_NAME = "M_CUST_NAME";
        
        private string _M_CARD_NO;
        
        /// <summary>
        /// M_CARD_NO
        /// </summary>
        public static string M_M_CARD_NO = "M_CARD_NO";
        
        private decimal _M_BALANCE;
        
        /// <summary>
        /// M_BALANCE
        /// </summary>
        public static string M_M_BALANCE = "M_BALANCE";
        
        private string _M_DEBT_DATE;
        
        /// <summary>
        /// M_DEBT_DATE
        /// </summary>
        public static string M_M_DEBT_DATE = "M_DEBT_DATE";
        
        private decimal _M_DEBT_AMT;
        
        /// <summary>
        /// M_DEBT_AMT
        /// </summary>
        public static string M_M_DEBT_AMT = "M_DEBT_AMT";
        
        private decimal _M_DEBT_BALANCE;
        
        /// <summary>
        /// M_DEBT_BALANCE
        /// </summary>
        public static string M_M_DEBT_BALANCE = "M_DEBT_BALANCE";
        
        private string _M_LAST_PAY_DATE;
        
        /// <summary>
        /// M_LAST_PAY_DATE
        /// </summary>
        public static string M_M_LAST_PAY_DATE = "M_LAST_PAY_DATE";
        
        private decimal _M_TOTAL_PAYMENT;
        
        /// <summary>
        /// M_TOTAL_PAYMENT
        /// </summary>
        public static string M_M_TOTAL_PAYMENT = "M_TOTAL_PAYMENT";
        
        private string _M_CLOSE_DATE;
        
        /// <summary>
        /// M_CLOSE_DATE
        /// </summary>
        public static string M_M_CLOSE_DATE = "M_CLOSE_DATE";
        
        private string _M_CLOSE_REASON;
        
        /// <summary>
        /// M_CLOSE_REASON
        /// </summary>
        public static string M_M_CLOSE_REASON = "M_CLOSE_REASON";
        
        private string _M_CLOSE_REP;
        
        /// <summary>
        /// M_CLOSE_REP
        /// </summary>
        public static string M_M_CLOSE_REP = "M_CLOSE_REP";
        
        /// <summary>
        /// M_CUST_ID
        /// </summary>
        [AttributeField("M_CUST_ID", "System.String", false, false, false, "String")]
        public string M_CUST_ID
        {
            get
            {
                return this._M_CUST_ID;
            }
            set
            {
                this._M_CUST_ID = value;
            }
        }
        
        /// <summary>
        /// M_CUST_NAME
        /// </summary>
        [AttributeField("M_CUST_NAME", "System.String", false, false, false, "String")]
        public string M_CUST_NAME
        {
            get
            {
                return this._M_CUST_NAME;
            }
            set
            {
                this._M_CUST_NAME = value;
            }
        }
        
        /// <summary>
        /// M_CARD_NO
        /// </summary>
        [AttributeField("M_CARD_NO", "System.String", false, false, false, "String")]
        public string M_CARD_NO
        {
            get
            {
                return this._M_CARD_NO;
            }
            set
            {
                this._M_CARD_NO = value;
            }
        }
        
        /// <summary>
        /// M_BALANCE
        /// </summary>
        [AttributeField("M_BALANCE", "System.Decimal", false, false, false, "Decimal")]
        public decimal M_BALANCE
        {
            get
            {
                return this._M_BALANCE;
            }
            set
            {
                this._M_BALANCE = value;
            }
        }
        
        /// <summary>
        /// M_DEBT_DATE
        /// </summary>
        [AttributeField("M_DEBT_DATE", "System.String", false, false, false, "String")]
        public string M_DEBT_DATE
        {
            get
            {
                return this._M_DEBT_DATE;
            }
            set
            {
                this._M_DEBT_DATE = value;
            }
        }
        
        /// <summary>
        /// M_DEBT_AMT
        /// </summary>
        [AttributeField("M_DEBT_AMT", "System.Decimal", false, false, false, "Decimal")]
        public decimal M_DEBT_AMT
        {
            get
            {
                return this._M_DEBT_AMT;
            }
            set
            {
                this._M_DEBT_AMT = value;
            }
        }
        
        /// <summary>
        /// M_DEBT_BALANCE
        /// </summary>
        [AttributeField("M_DEBT_BALANCE", "System.Decimal", false, false, false, "Decimal")]
        public decimal M_DEBT_BALANCE
        {
            get
            {
                return this._M_DEBT_BALANCE;
            }
            set
            {
                this._M_DEBT_BALANCE = value;
            }
        }
        
        /// <summary>
        /// M_LAST_PAY_DATE
        /// </summary>
        [AttributeField("M_LAST_PAY_DATE", "System.String", false, false, false, "String")]
        public string M_LAST_PAY_DATE
        {
            get
            {
                return this._M_LAST_PAY_DATE;
            }
            set
            {
                this._M_LAST_PAY_DATE = value;
            }
        }
        
        /// <summary>
        /// M_TOTAL_PAYMENT
        /// </summary>
        [AttributeField("M_TOTAL_PAYMENT", "System.Decimal", false, false, false, "Decimal")]
        public decimal M_TOTAL_PAYMENT
        {
            get
            {
                return this._M_TOTAL_PAYMENT;
            }
            set
            {
                this._M_TOTAL_PAYMENT = value;
            }
        }
        
        /// <summary>
        /// M_CLOSE_DATE
        /// </summary>
        [AttributeField("M_CLOSE_DATE", "System.String", false, false, false, "String")]
        public string M_CLOSE_DATE
        {
            get
            {
                return this._M_CLOSE_DATE;
            }
            set
            {
                this._M_CLOSE_DATE = value;
            }
        }
        
        /// <summary>
        /// M_CLOSE_REASON
        /// </summary>
        [AttributeField("M_CLOSE_REASON", "System.String", false, false, false, "String")]
        public string M_CLOSE_REASON
        {
            get
            {
                return this._M_CLOSE_REASON;
            }
            set
            {
                this._M_CLOSE_REASON = value;
            }
        }
        
        /// <summary>
        /// M_CLOSE_REP
        /// </summary>
        [AttributeField("M_CLOSE_REP", "System.String", false, false, false, "String")]
        public string M_CLOSE_REP
        {
            get
            {
                return this._M_CLOSE_REP;
            }
            set
            {
                this._M_CLOSE_REP = value;
            }
        }
    }
    
    /// <summary>
    /// Pay_Macro
    /// </summary>
    [Serializable()]
    public class EntityPay_MacroSet : EntitySet<EntityPay_Macro>
    {
    }
}
