//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.832
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPPayCertify.EntityLayer
{
    
    
    /// <summary>
    /// EntityPay_SV_Tmp
    /// </summary>
    [Serializable()]
    [AttributeTable("Pay_SV_Tmp")]
    public class EntityPay_SV_Tmp : Entity
    {
        
        private string _UserID;
        
        /// <summary>
        /// UserID
        /// </summary>
        public static string M_UserID = "UserID";
        
        private string _UserName;
        
        /// <summary>
        /// UserName
        /// </summary>
        public static string M_UserName = "UserName";
        
        private string _ApplyDate;
        
        /// <summary>
        /// ApplyDate
        /// </summary>
        public static string M_ApplyDate = "ApplyDate";
        
        private string _Status;
        
        /// <summary>
        /// Status
        /// </summary>
        public static string M_Status = "Status";
        
        private string _Address;
        
        /// <summary>
        /// Address
        /// </summary>
        public static string M_Address = "Address";
        
        private string _ApplyUser;
        
        /// <summary>
        /// ApplyUser
        /// </summary>
        public static string M_ApplyUser = "ApplyUser";
        
        private string _AgreeUser;
        
        /// <summary>
        /// AgreeUser
        /// </summary>
        public static string M_AgreeUser = "AgreeUser";
        
        private string _ClearDate;
        
        /// <summary>
        /// ClearDate
        /// </summary>
        public static string M_ClearDate = "ClearDate";
        
        private string _Enddate;
        
        /// <summary>
        /// Enddate
        /// </summary>
        public static string M_Enddate = "Enddate";
        
        private string _Consignee;
        
        /// <summary>
        /// Consignee
        /// </summary>
        public static string M_Consignee = "Consignee";
        
        private string _CardNo;
        
        /// <summary>
        /// CardNo
        /// </summary>
        public static string M_CardNo = "CardNo";
        
        private string _BLKCode;
        
        /// <summary>
        /// BLKCode
        /// </summary>
        public static string M_BLKCode = "BLKCode";
        
        private string _CardType;
        
        /// <summary>
        /// CardType
        /// </summary>
        public static string M_CardType = "CardType";
        
        private string _CardName;
        
        /// <summary>
        /// CardName
        /// </summary>
        public static string M_CardName = "CardName";
        
        private string _CardID;
        
        /// <summary>
        /// CardID
        /// </summary>
        public static string M_CardID = "CardID";
        
        private string _IsPaidOffAlone;
        
        /// <summary>
        /// IsPaidOffAlone
        /// </summary>
        public static string M_IsPaidOffAlone = "IsPaidOffAlone";
        
        private string _case_no;
        
        /// <summary>
        /// case_no
        /// </summary>
        public static string M_case_no = "case_no";
        
        private System.Nullable<int> _SeqNo;
        
        /// <summary>
        /// SeqNo
        /// </summary>
        public static string M_SeqNo = "SeqNo";
        
        private string _IsCheck;
        
        /// <summary>
        /// IsCheck
        /// </summary>
        public static string M_IsCheck = "IsCheck";
        
        private string _IsReback;
        
        /// <summary>
        /// IsReback
        /// </summary>
        public static string M_IsReback = "IsReback";
        
        private string _IsADD;
        
        /// <summary>
        /// IsADD
        /// </summary>
        public static string M_IsADD = "IsADD";
        
        private System.Nullable<int> _CheckTime;
        
        /// <summary>
        /// CheckTime
        /// </summary>
        public static string M_CheckTime = "CheckTime";
        
        private string _RebackReason;
        
        /// <summary>
        /// RebackReason
        /// </summary>
        public static string M_RebackReason = "RebackReason";
        
        /// <summary>
        /// UserID
        /// </summary>
        [AttributeField("UserID", "System.String", false, false, false, "String")]
        public string UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this._UserID = value;
            }
        }
        
        /// <summary>
        /// UserName
        /// </summary>
        [AttributeField("UserName", "System.String", false, false, false, "String")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this._UserName = value;
            }
        }
        
        /// <summary>
        /// ApplyDate
        /// </summary>
        [AttributeField("ApplyDate", "System.String", false, false, false, "String")]
        public string ApplyDate
        {
            get
            {
                return this._ApplyDate;
            }
            set
            {
                this._ApplyDate = value;
            }
        }
        
        /// <summary>
        /// Status
        /// </summary>
        [AttributeField("Status", "System.String", false, false, false, "String")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this._Status = value;
            }
        }
        
        /// <summary>
        /// Address
        /// </summary>
        [AttributeField("Address", "System.String", false, false, false, "String")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this._Address = value;
            }
        }
        
        /// <summary>
        /// ApplyUser
        /// </summary>
        [AttributeField("ApplyUser", "System.String", false, false, false, "String")]
        public string ApplyUser
        {
            get
            {
                return this._ApplyUser;
            }
            set
            {
                this._ApplyUser = value;
            }
        }
        
        /// <summary>
        /// AgreeUser
        /// </summary>
        [AttributeField("AgreeUser", "System.String", false, false, false, "String")]
        public string AgreeUser
        {
            get
            {
                return this._AgreeUser;
            }
            set
            {
                this._AgreeUser = value;
            }
        }
        
        /// <summary>
        /// ClearDate
        /// </summary>
        [AttributeField("ClearDate", "System.String", false, false, false, "String")]
        public string ClearDate
        {
            get
            {
                return this._ClearDate;
            }
            set
            {
                this._ClearDate = value;
            }
        }
        
        /// <summary>
        /// Enddate
        /// </summary>
        [AttributeField("Enddate", "System.String", false, false, false, "String")]
        public string Enddate
        {
            get
            {
                return this._Enddate;
            }
            set
            {
                this._Enddate = value;
            }
        }
        
        /// <summary>
        /// Consignee
        /// </summary>
        [AttributeField("Consignee", "System.String", false, false, false, "String")]
        public string Consignee
        {
            get
            {
                return this._Consignee;
            }
            set
            {
                this._Consignee = value;
            }
        }
        
        /// <summary>
        /// CardNo
        /// </summary>
        [AttributeField("CardNo", "System.String", false, false, false, "String")]
        public string CardNo
        {
            get
            {
                return this._CardNo;
            }
            set
            {
                this._CardNo = value;
            }
        }
        
        /// <summary>
        /// BLKCode
        /// </summary>
        [AttributeField("BLKCode", "System.String", false, false, false, "String")]
        public string BLKCode
        {
            get
            {
                return this._BLKCode;
            }
            set
            {
                this._BLKCode = value;
            }
        }
        
        /// <summary>
        /// CardType
        /// </summary>
        [AttributeField("CardType", "System.String", false, false, false, "String")]
        public string CardType
        {
            get
            {
                return this._CardType;
            }
            set
            {
                this._CardType = value;
            }
        }
        
        /// <summary>
        /// CardName
        /// </summary>
        [AttributeField("CardName", "System.String", false, false, false, "String")]
        public string CardName
        {
            get
            {
                return this._CardName;
            }
            set
            {
                this._CardName = value;
            }
        }
        
        /// <summary>
        /// CardID
        /// </summary>
        [AttributeField("CardID", "System.String", false, false, false, "String")]
        public string CardID
        {
            get
            {
                return this._CardID;
            }
            set
            {
                this._CardID = value;
            }
        }
        
        /// <summary>
        /// IsPaidOffAlone
        /// </summary>
        [AttributeField("IsPaidOffAlone", "System.String", false, false, false, "String")]
        public string IsPaidOffAlone
        {
            get
            {
                return this._IsPaidOffAlone;
            }
            set
            {
                this._IsPaidOffAlone = value;
            }
        }
        
        /// <summary>
        /// case_no
        /// </summary>
        [AttributeField("case_no", "System.String", false, false, false, "String")]
        public string case_no
        {
            get
            {
                return this._case_no;
            }
            set
            {
                this._case_no = value;
            }
        }
        
        /// <summary>
        /// SeqNo
        /// </summary>
        [AttributeField("SeqNo", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> SeqNo
        {
            get
            {
                return this._SeqNo;
            }
            set
            {
                this._SeqNo = value;
            }
        }
        
        /// <summary>
        /// IsCheck
        /// </summary>
        [AttributeField("IsCheck", "System.String", false, false, false, "String")]
        public string IsCheck
        {
            get
            {
                return this._IsCheck;
            }
            set
            {
                this._IsCheck = value;
            }
        }
        
        /// <summary>
        /// IsReback
        /// </summary>
        [AttributeField("IsReback", "System.String", false, false, false, "String")]
        public string IsReback
        {
            get
            {
                return this._IsReback;
            }
            set
            {
                this._IsReback = value;
            }
        }
        
        /// <summary>
        /// IsADD
        /// </summary>
        [AttributeField("IsADD", "System.String", false, false, false, "String")]
        public string IsADD
        {
            get
            {
                return this._IsADD;
            }
            set
            {
                this._IsADD = value;
            }
        }
        
        /// <summary>
        /// CheckTime
        /// </summary>
        [AttributeField("CheckTime", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> CheckTime
        {
            get
            {
                return this._CheckTime;
            }
            set
            {
                this._CheckTime = value;
            }
        }
        
        /// <summary>
        /// RebackReason
        /// </summary>
        [AttributeField("RebackReason", "System.String", false, false, false, "String")]
        public string RebackReason
        {
            get
            {
                return this._RebackReason;
            }
            set
            {
                this._RebackReason = value;
            }
        }
    }
    
    /// <summary>
    /// EntityPay_SV_Tmp
    /// </summary>
    [Serializable()]
    public class EntityPay_SV_TmpSet : EntitySet<EntityPay_SV_Tmp>
    {
    }
}
