//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.832
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;



namespace CSIPPayCertify.EntityLayer
{
    
    
    /// <summary>
    /// EntitySet_SelfOther
    /// </summary>
    [Serializable()]
    [AttributeTable("Set_SelfOther")]
    public class EntitySet_SelfOther : Entity
    {
        
        private string _SerialNo;
        
        /// <summary>
        /// SerialNo
        /// </summary>
        public static string M_SerialNo = "SerialNo";
        
        private string _SelfDay;
        
        /// <summary>
        /// SelfDay
        /// </summary>
        public static string M_SelfDay = "SelfDay";
        
        private string _OtherDay;
        
        /// <summary>
        /// OtherDay
        /// </summary>
        public static string M_OtherDay = "OtherDay";
        
        private string _Note;
        
        /// <summary>
        /// Note
        /// </summary>
        public static string M_Note = "Note";
        
        /// <summary>
        /// SerialNo
        /// </summary>
        [AttributeField("SerialNo", "System.String", false, false, false, "String")]
        public string SerialNo
        {
            get
            {
                return this._SerialNo;
            }
            set
            {
                this._SerialNo = value;
            }
        }
        
        /// <summary>
        /// SelfDay
        /// </summary>
        [AttributeField("SelfDay", "System.String", false, false, false, "String")]
        public string SelfDay
        {
            get
            {
                return this._SelfDay;
            }
            set
            {
                this._SelfDay = value;
            }
        }
        
        /// <summary>
        /// OtherDay
        /// </summary>
        [AttributeField("OtherDay", "System.String", false, false, false, "String")]
        public string OtherDay
        {
            get
            {
                return this._OtherDay;
            }
            set
            {
                this._OtherDay = value;
            }
        }
        
        /// <summary>
        /// Note
        /// </summary>
        [AttributeField("Note", "System.String", false, false, false, "String")]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this._Note = value;
            }
        }
    }
    
    /// <summary>
    /// Set_SelfOther
    /// </summary>
    [Serializable()]
    public class EntitySet_SelfOtherSet : EntitySet<EntitySet_SelfOther>
    {
    }
}
