//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.832
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPPayCertify.EntityLayer
{
    
    
    /// <summary>
    /// Set_Pay_Certify
    /// </summary>
    [Serializable()]
    [AttributeTable("ML2PL")]
    public class EntityML2PL : Entity
    {
        
        private string _ID;
        public static string M_ID = "ID";
        
        private string _CARD_NO;
        public static string M_CARD_NO = "CARD_NO";
        

        [AttributeField("ID", "System.String", false, false, false, "String")]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }
        
        [AttributeField("CARD_NO", "System.String", false, false, false, "String")]
        public string CARD_NO
        {
            get
            {
                return this._CARD_NO;
            }
            set
            {
                this._CARD_NO = value;
            }
        }
        

    }
    
    /// <summary>
    /// ML2PL
    /// </summary>
    [Serializable()]
    public class EntityML2PLSet : EntitySet<EntityML2PL>
    {
    }
}
