//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.832
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPPayCertify.EntityLayer
{
    
    
    /// <summary>
    /// EntityPay_SV
    /// </summary>
    [Serializable()]
    [AttributeTable("Pay_SV")]
    public class EntityPay_SV : Entity
    {
        
        private string _SerialNo;
        
        /// <summary>
        /// SerialNo
        /// </summary>
        public static string M_SerialNo = "SerialNo";
        
        private string _UserID;
        
        /// <summary>
        /// UserID
        /// </summary>
        public static string M_UserID = "UserID";
        
        private string _UserName;
        
        /// <summary>
        /// UserName
        /// </summary>
        public static string M_UserName = "UserName";
        
        private string _ApplyDate;
        
        /// <summary>
        /// ApplyDate
        /// </summary>
        public static string M_ApplyDate = "ApplyDate";
        
        private string _Status;
        
        /// <summary>
        /// Status
        /// </summary>
        public static string M_Status = "Status";
        
        private string _ApplyUser;
        
        /// <summary>
        /// ApplyUser
        /// </summary>
        public static string M_ApplyUser = "ApplyUser";
        
        private string _AgreeUser;
        
        /// <summary>
        /// AgreeUser
        /// </summary>
        public static string M_AgreeUser = "AgreeUser";
        
        private string _ClearDate;
        
        /// <summary>
        /// ClearDate
        /// </summary>
        public static string M_ClearDate = "ClearDate";
        
        private string _Enddate;
        
        /// <summary>
        /// Enddate
        /// </summary>
        public static string M_Enddate = "Enddate";
        
        private string _Consignee;
        
        /// <summary>
        /// Consignee
        /// </summary>
        public static string M_Consignee = "Consignee";
        
        private string _BLKCode;
        
        /// <summary>
        /// BLKCode
        /// </summary>
        public static string M_BLKCode = "BLKCode";
        
        private string _Add1;
        
        /// <summary>
        /// Add1
        /// </summary>
        public static string M_Add1 = "Add1";
        
        private string _Zip;
        
        /// <summary>
        /// Zip
        /// </summary>
        public static string M_Zip = "Zip";
        
        private string _Add2;
        
        /// <summary>
        /// Add2
        /// </summary>
        public static string M_Add2 = "Add2";
        
        private string _Add3;
        
        /// <summary>
        /// Add3
        /// </summary>
        public static string M_Add3 = "Add3";
        
        private string _MailDay;
        
        /// <summary>
        /// MailDay
        /// </summary>
        public static string M_MailDay = "MailDay";
        
        private string _MailNo;
        
        /// <summary>
        /// MailNo
        /// </summary>
        public static string M_MailNo = "MailNo";
        
        private string _Note;
        
        /// <summary>
        /// Note
        /// </summary>
        public static string M_Note = "Note";
        
        private string _MakeUp;
        
        /// <summary>
        /// MakeUp
        /// </summary>
        public static string M_MakeUp = "MakeUp";
        
        private string _MakeUpDate;
        
        /// <summary>
        /// MakeUpDate
        /// </summary>
        public static string M_MakeUpDate = "MakeUpDate";
        
        private string _MailMethod;
        
        /// <summary>
        /// MailMethod
        /// </summary>
        public static string M_MailMethod = "MailMethod";
        
        private string _ShowExtra;
        
        /// <summary>
        /// ShowExtra
        /// </summary>
        public static string M_ShowExtra = "ShowExtra";
        
        private string _GetFee;
        
        /// <summary>
        /// GetFee
        /// </summary>
        public static string M_GetFee = "GetFee";
        
        private string _IsMail;
        
        /// <summary>
        /// IsMail
        /// </summary>
        public static string M_IsMail = "IsMail";
        
        private string _KeyinDay;
        
        /// <summary>
        /// KeyinDay
        /// </summary>
        public static string M_KeyinDay = "KeyinDay";
        
        private string _Type;
        
        /// <summary>
        /// Type
        /// </summary>
        public static string M_Type = "Type";
        
        private string _void;
        
        /// <summary>
        /// void
        /// </summary>
        public static string M_void = "void";
        
        private string _CardType;
        
        /// <summary>
        /// CardType
        /// </summary>
        public static string M_CardType = "CardType";
        
        private string _CreateDate;
        
        /// <summary>
        /// CreateDate
        /// </summary>
        public static string M_CreateDate = "CreateDate";
        
        private string _IsPrinted;
        
        /// <summary>
        /// IsPrinted
        /// </summary>
        public static string M_IsPrinted = "IsPrinted";
        
        private string _IsPaidOffAlone;
        
        /// <summary>
        /// IsPaidOffAlone
        /// </summary>
        public static string M_IsPaidOffAlone = "IsPaidOffAlone";
        
        /// <summary>
        /// SerialNo
        /// </summary>
        [AttributeField("SerialNo", "System.String", false, false, false, "String")]
        public string SerialNo
        {
            get
            {
                return this._SerialNo;
            }
            set
            {
                this._SerialNo = value;
            }
        }
        
        /// <summary>
        /// UserID
        /// </summary>
        [AttributeField("UserID", "System.String", false, false, false, "String")]
        public string UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this._UserID = value;
            }
        }
        
        /// <summary>
        /// UserName
        /// </summary>
        [AttributeField("UserName", "System.String", false, false, false, "String")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this._UserName = value;
            }
        }
        
        /// <summary>
        /// ApplyDate
        /// </summary>
        [AttributeField("ApplyDate", "System.String", false, false, false, "String")]
        public string ApplyDate
        {
            get
            {
                return this._ApplyDate;
            }
            set
            {
                this._ApplyDate = value;
            }
        }
        
        /// <summary>
        /// Status
        /// </summary>
        [AttributeField("Status", "System.String", false, false, false, "String")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this._Status = value;
            }
        }
        
        /// <summary>
        /// ApplyUser
        /// </summary>
        [AttributeField("ApplyUser", "System.String", false, false, false, "String")]
        public string ApplyUser
        {
            get
            {
                return this._ApplyUser;
            }
            set
            {
                this._ApplyUser = value;
            }
        }
        
        /// <summary>
        /// AgreeUser
        /// </summary>
        [AttributeField("AgreeUser", "System.String", false, false, false, "String")]
        public string AgreeUser
        {
            get
            {
                return this._AgreeUser;
            }
            set
            {
                this._AgreeUser = value;
            }
        }
        
        /// <summary>
        /// ClearDate
        /// </summary>
        [AttributeField("ClearDate", "System.String", false, false, false, "String")]
        public string ClearDate
        {
            get
            {
                return this._ClearDate;
            }
            set
            {
                this._ClearDate = value;
            }
        }
        
        /// <summary>
        /// Enddate
        /// </summary>
        [AttributeField("Enddate", "System.String", false, false, false, "String")]
        public string Enddate
        {
            get
            {
                return this._Enddate;
            }
            set
            {
                this._Enddate = value;
            }
        }
        
        /// <summary>
        /// Consignee
        /// </summary>
        [AttributeField("Consignee", "System.String", false, false, false, "String")]
        public string Consignee
        {
            get
            {
                return this._Consignee;
            }
            set
            {
                this._Consignee = value;
            }
        }
        
        /// <summary>
        /// BLKCode
        /// </summary>
        [AttributeField("BLKCode", "System.String", false, false, false, "String")]
        public string BLKCode
        {
            get
            {
                return this._BLKCode;
            }
            set
            {
                this._BLKCode = value;
            }
        }
        
        /// <summary>
        /// Add1
        /// </summary>
        [AttributeField("Add1", "System.String", false, false, false, "String")]
        public string Add1
        {
            get
            {
                return this._Add1;
            }
            set
            {
                this._Add1 = value;
            }
        }
        
        /// <summary>
        /// Zip
        /// </summary>
        [AttributeField("Zip", "System.String", false, false, false, "String")]
        public string Zip
        {
            get
            {
                return this._Zip;
            }
            set
            {
                this._Zip = value;
            }
        }
        
        /// <summary>
        /// Add2
        /// </summary>
        [AttributeField("Add2", "System.String", false, false, false, "String")]
        public string Add2
        {
            get
            {
                return this._Add2;
            }
            set
            {
                this._Add2 = value;
            }
        }
        
        /// <summary>
        /// Add3
        /// </summary>
        [AttributeField("Add3", "System.String", false, false, false, "String")]
        public string Add3
        {
            get
            {
                return this._Add3;
            }
            set
            {
                this._Add3 = value;
            }
        }
        
        /// <summary>
        /// MailDay
        /// </summary>
        [AttributeField("MailDay", "System.String", false, false, false, "String")]
        public string MailDay
        {
            get
            {
                return this._MailDay;
            }
            set
            {
                this._MailDay = value;
            }
        }
        
        /// <summary>
        /// MailNo
        /// </summary>
        [AttributeField("MailNo", "System.String", false, false, false, "String")]
        public string MailNo
        {
            get
            {
                return this._MailNo;
            }
            set
            {
                this._MailNo = value;
            }
        }
        
        /// <summary>
        /// Note
        /// </summary>
        [AttributeField("Note", "System.String", false, false, false, "String")]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this._Note = value;
            }
        }
        
        /// <summary>
        /// MakeUp
        /// </summary>
        [AttributeField("MakeUp", "System.String", false, false, false, "String")]
        public string MakeUp
        {
            get
            {
                return this._MakeUp;
            }
            set
            {
                this._MakeUp = value;
            }
        }
        
        /// <summary>
        /// MakeUpDate
        /// </summary>
        [AttributeField("MakeUpDate", "System.String", false, false, false, "String")]
        public string MakeUpDate
        {
            get
            {
                return this._MakeUpDate;
            }
            set
            {
                this._MakeUpDate = value;
            }
        }
        
        /// <summary>
        /// MailMethod
        /// </summary>
        [AttributeField("MailMethod", "System.String", false, false, false, "String")]
        public string MailMethod
        {
            get
            {
                return this._MailMethod;
            }
            set
            {
                this._MailMethod = value;
            }
        }
        
        /// <summary>
        /// ShowExtra
        /// </summary>
        [AttributeField("ShowExtra", "System.String", false, false, false, "String")]
        public string ShowExtra
        {
            get
            {
                return this._ShowExtra;
            }
            set
            {
                this._ShowExtra = value;
            }
        }
        
        /// <summary>
        /// GetFee
        /// </summary>
        [AttributeField("GetFee", "System.String", false, false, false, "String")]
        public string GetFee
        {
            get
            {
                return this._GetFee;
            }
            set
            {
                this._GetFee = value;
            }
        }
        
        /// <summary>
        /// IsMail
        /// </summary>
        [AttributeField("IsMail", "System.String", false, false, false, "String")]
        public string IsMail
        {
            get
            {
                return this._IsMail;
            }
            set
            {
                this._IsMail = value;
            }
        }
        
        /// <summary>
        /// KeyinDay
        /// </summary>
        [AttributeField("KeyinDay", "System.String", false, false, false, "String")]
        public string KeyinDay
        {
            get
            {
                return this._KeyinDay;
            }
            set
            {
                this._KeyinDay = value;
            }
        }
        
        /// <summary>
        /// Type
        /// </summary>
        [AttributeField("Type", "System.String", false, false, false, "String")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this._Type = value;
            }
        }
        
        /// <summary>
        /// void
        /// </summary>
        [AttributeField("void", "System.String", false, false, false, "String")]
        public string @void
        {
            get
            {
                return this._void;
            }
            set
            {
                this._void = value;
            }
        }
        
        /// <summary>
        /// CardType
        /// </summary>
        [AttributeField("CardType", "System.String", false, false, false, "String")]
        public string CardType
        {
            get
            {
                return this._CardType;
            }
            set
            {
                this._CardType = value;
            }
        }
        
        /// <summary>
        /// CreateDate
        /// </summary>
        [AttributeField("CreateDate", "System.String", false, false, false, "String")]
        public string CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this._CreateDate = value;
            }
        }
        
        /// <summary>
        /// IsPrinted
        /// </summary>
        [AttributeField("IsPrinted", "System.String", false, false, false, "String")]
        public string IsPrinted
        {
            get
            {
                return this._IsPrinted;
            }
            set
            {
                this._IsPrinted = value;
            }
        }
        
        /// <summary>
        /// IsPaidOffAlone
        /// </summary>
        [AttributeField("IsPaidOffAlone", "System.String", false, false, false, "String")]
        public string IsPaidOffAlone
        {
            get
            {
                return this._IsPaidOffAlone;
            }
            set
            {
                this._IsPaidOffAlone = value;
            }
        }
    }
    
    /// <summary>
    /// EntityPay_SV
    /// </summary>
    [Serializable()]
    public class EntityPay_SVSet : EntitySet<EntityPay_SV>
    {
    }
}
