//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.832
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPPayCertify.EntityLayer
{
    
    
    /// <summary>
    /// EntityPay_Return
    /// </summary>
    [Serializable()]
    [AttributeTable("Pay_Return")]
    public class EntityPay_Return : Entity
    {
        
        private string _serialNo;
        
        /// <summary>
        /// serialNo
        /// </summary>
        public static string M_serialNo = "serialNo";
        
        private string _userID;
        
        /// <summary>
        /// userID
        /// </summary>
        public static string M_userID = "userID";
        
        private string _returnDay;
        
        /// <summary>
        /// returnDay
        /// </summary>
        public static string M_returnDay = "returnDay";
        
        private string _returnReason;
        
        /// <summary>
        /// returnReason
        /// </summary>
        public static string M_returnReason = "returnReason";
        
        /// <summary>
        /// serialNo
        /// </summary>
        [AttributeField("serialNo", "System.String", false, false, false, "String")]
        public string serialNo
        {
            get
            {
                return this._serialNo;
            }
            set
            {
                this._serialNo = value;
            }
        }
        
        /// <summary>
        /// userID
        /// </summary>
        [AttributeField("userID", "System.String", false, false, false, "String")]
        public string userID
        {
            get
            {
                return this._userID;
            }
            set
            {
                this._userID = value;
            }
        }
        
        /// <summary>
        /// returnDay
        /// </summary>
        [AttributeField("returnDay", "System.String", false, false, false, "String")]
        public string returnDay
        {
            get
            {
                return this._returnDay;
            }
            set
            {
                this._returnDay = value;
            }
        }
        
        /// <summary>
        /// returnReason
        /// </summary>
        [AttributeField("returnReason", "System.String", false, false, false, "String")]
        public string returnReason
        {
            get
            {
                return this._returnReason;
            }
            set
            {
                this._returnReason = value;
            }
        }
    }
    
    /// <summary>
    /// EntityPay_Return
    /// </summary>
    [Serializable()]
    public class EntityPay_ReturnSet : EntitySet<EntityPay_Return>
    {
    }
}
